name: env-vars-example
on:
  push:

# ::span-comment
# 워크플로우 전체 대한 환경변수를 설정할 수 있습니다.
env:
  VENI: 'I came'
# ::end-span

jobs:
  use-env-vars:
    runs-on: ubuntu-latest
    # ::span-comment
    # 특정 작업에 대해 환경 변수를 설정 할 수 있습니다.
    env:
      VIDI: 'I saw'
    # ::end-span
    steps:
      -
        name: Show me the vars
        # 운영체제에서 환경변수를 사용하는 일반적인 방법으로 사용 할 수 있습니다.
        run: echo "$VENI, $VIDI, $VICI"
        # 각 `step`별 환경 변수를 설정 할 수 있습니다.
        env:
          VICI: 'I conquered'

      -
        name: Create env var
        # `GITHUB_ENV`변수의 파일에 한줄을 추가하여 새로운 환경변수를 설정합니다.
        # 이 환경 변수는 이후의 모든 `step`에서 사용 가능합니다.
        # 참고 : 다음 `step`전에는 `GITHUB_ENV`에 따라 환경변수가 업데이트 되지 않습니다.
        run: echo "foo=bar" >> $GITHUB_ENV

      -
        name: Useful default vars
        run: |

        # ::span-comment
        # 기본적으로 사용할수 있는 환경변수가 많이 있습니다.
        # 아래 예제는 일부분입니다. [전체 리스트 보기](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)를 클릭하여 확인 해보세요.
          echo "Workflow name:  $GITHUB_WORKFLOW
          echo "Workspace:      $GITHUB_WORKSPACE"
          echo "Event:          $GITHUB_EVENT_NAME"
          echo "SHA:            $GITHUB_SHA"
          echo "Ref:            $GITHUB_REF"
        # ::end-span
