# job `matrix`를 사용하여 다른 설정에서 여러 job을 실행할수있습니다.
# `matrix`로 정의된 job은 기본적으로 병렬로 실행 되는 점을 유의해야합니다.

name: job-matrix
on:
  push:

jobs:
  my-job:
    strategy:
      # ::span-comment
      # `matrix`키워드로 job matrix를 정의합니다.
      # 각 사용자 정의 키는 matrix 파라미터입니다, 아래 예제는 `os`와 `node` 두가지를 정의 했습니다.
      # [데카르트 곱](https://ko.wikipedia.org/wiki/%EA%B3%B1%EC%A7%91%ED%95%A9)의 각 파라미터에 가능한 값 목록은 job을 만드는 데 사용됩니다.
      # 이 섹션은 `os`와 `node`의 각각 다른 조합인 6개의 job으로 구성된 2 x 3 matrix를 정의 합니다.
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [6, 8, 10]
      # ::end-span

        # ::span-comment
        # 'exclude' 키워드는 실행중 특정 구성에서 job이 실행되지 않도록 합니다.
        exclude:
          -
            os: ubuntu-16.04
            node: 6
        # ::end-span

        # ::span-comment
        # `include` 키워드를 사용하여 `matrix`에 새로운 job을 추가할 수 있습니다.
        # `include`은 항상 `exclude` 다음에 평가됩니다.
        include:
          -
            os: macos-latest
            node: 10
        # ::end-span

    # `matrix` 파라미터를 사용하여 job을 설정합니다.
    # [컨텍스트 표현식](index.html)은 파라미터 값을 삽입하는 데 사용됩니다.
    # 이 예제에서는 'os' 매개 변수를 사용하여 job의 운영 체제를 설정합니다.
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/setup-node@2
        with:
          # Setup node based on the matrix parameter `node`
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
