# 액션은 일반적인 작업을 재사용 가능한 "코드"로 제공하여 워크플로우의 단계를 줄일수있습니다.
# 작업을 지정하려면 `uses` 키워드와 `{owner}/{repo}@{ref}` 또는 `{owner}/{repo}/{path}@{ref}`
# 형태의 Github 저장소를 지정하는 패턴을 입력합니다.
# 만약 서브 디렉토리인 경우 `ref`는 브랜치나 태그, SHA값을 입력할수있습니다

name: actions-example
on:
  push:

jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      # `checkout`액션은 작업 디렉토리로 워크플로우를 트리거한 저장소를 체크아웃 합니다 (예: 푸시된 브랜치)
      - uses: actions/checkout@v2
      # `setup-node`액션으로 다음 작업부터 노드와 npm을 사용할 수 있습니다
      - uses: actions/setup-node@v1
        # ::span-comment
        # 몇몇 액션들은 필수인수나 선택인수가 있습니다.
        with:
          node-version: '15.8.0'
        # ::end-span

      -
        name: Install repo dependencies
        run: npm install
      -
        name: Run script from repo
        run: node helloWorld.js
